### ISSUE TITLE
Retrieving data for possible goals

### ISSUE THREAD

**Issue by Der-Eddy** [RoadFromGreedfest/Road-From-Greedfest#11]
I'm currently working on a way to scrape all the data which would be probably useful for goals for the greedfest like "Get under X concurrent players", "Get the Metacritic Userscore below 3" or "Get the Steam Reveiw Rating to mixed"

Things like current player, metacritic score (NOT Userscore) and total of steam reviews are easy retrievable through the steam api  
my progress so far can be found here: https://github.com/Der-Eddy/metacritic-steam-score-scrapper

it's under MIT License so feel free to do whatever you want with it  
the next thing will be to scrape the metacritic and steam store site since metacritic lacks an public api and steams store api is rather limited, maybe someone has a suggestion or knows a better way

the current output looks like this:  
```json
{

    "response": 

    {

        "player_count": 24459,
        "player_count_minimum": 9200,
        "appid": 218620,
        "metacritic": 

            {

                "link": "http://www.metacritic.com/game/pc/payday-2",
                "score": 79,
                "user_score": 4.6

            },
        "steam": 

            {
                "link": "http://store.steampowered.com/app/218620/",
                "reviews_all": 154385,
                "reviews_positive": 123374,
                "reviews_negative": 31011
            }
    }

}
```

**Comment by florensie** [comment]
Great! This is the first real progress we (actually you) are making.

**Comment by RoadFromGreedfest** [comment]
https://market.mashape.com/byroredux/metacritic-v2

Looks like we could use this for metacritic scores if we don't want to scrape ourselves. We can do 1000 queries a day, 1 every ~2 mins

**Comment by RoadFromGreedfest** [comment]
Github doesn't support PHP, so we'll need to migrate to a fully fledged webhost at some point

**Comment by florensie** [comment]
I have a website but I don't know if you will like it if it is hosted on my domain. ( florens.be )

**Comment by Der-Eddy** [comment]
I'm almost done implementing the Metacritic Userscore, however it looks like the Metacritic Server doesn't like too many requests

btw. I implemented for the moment JSONP and CORS support (so you can call the JSONP Object via AJAX without needing a PHP Proxy for that) which can be found here: http://crimefest.eddydev.de/api/api.php (serving a normal JSON if without a callback)
but my webserver at the moment will only work for 17 days after today

**Comment by brianbrewer** [comment]
@Der-Eddy Looks good I'm adding JSONP at the moment; any chance you can scrape the percentage or negative / positive

**Comment by Der-Eddy** [comment]
@brianbrewer this is the next thing I wanted to do, however I didn't had much success with regex at the moment :/  
will try another approach after work

**Comment by Der-Eddy** [comment]
So, it should work for now

```json
{

    "response": 

    {

        "player_count": 24459,
        "player_count_minimum": 9200,
        "appid": 218620,
        "metacritic": 

            {

                "link": "http://www.metacritic.com/game/pc/payday-2",
                "score": 79,
                "user_score": 4.6

            },
        "steam": 

            {
                "link": "http://store.steampowered.com/app/218620/",
                "reviews_all": 154385,
                "reviews_positive": 123374,
                "reviews_negative": 31011
            }
    }

}
```

The Steamstore and Metacritic site sometimes doesn't load anything for my PHP Server, but thats probably more a problem on my site

**Comment by brianbrewer** [comment]
@Der-Eddy Awesome, I'll try hooking up some example challenges to these values

**Comment by Der-Eddy** [comment]
Looks like the Agecheck for PayDay2 currently makes problems, I will look into it

**Comment by Der-Eddy** [comment]
Steam Reviews and Metacritic Userscore now works like a charm  
for further discussions use the reddit topic: https://www.reddit.com/r/roadfromgreedfest/comments/3pj5pc/goals_for_greedfest_how_to_retrieve_them/
